version: '3.9'

services:
  postgres-db:
    image: 'postgres:latest'
    container_name: library-db
    environment:
      - 'POSTGRES_DB=library_db'
      - 'POSTGRES_USER=library_admin_user'
      - 'POSTGRES_PASSWORD=library_admin_password'
    ports:
      - '5433:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: